FROM node:lts AS builder
WORKDIR /app
COPY ./webui/package*.json ./
RUN npm ci
COPY ./webui .
ARG VITE_API_URL=""
RUN VITE_API_URL=$VITE_API_URL npm run build

FROM nginx:stable
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
