openapi: 3.1.0
servers:
  - url: "http://localhost:3000"
info:
  title: WASAText
  description: WASAText; "Programmazione per il Web 2025/26"'s project
  version: 0.0.1
paths:
  /session:
    post:
      tags: ["login"]
      summary: logs in the user 
      description: |- 
        If the user doesnt exit, it will be created, 
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Pippo
                  pattern: '^.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:  
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                    example: "ciao12345"
  /users/{userId}/username:
    put:
      summary: set username 
      description: the user set the username that other users will see while texting with him
      operationId: setMyUserName
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: UserName desired
        content: 
          application/json:
            schema: 
              type: object
              properties:
                UserName:
                  type: string
                  example: Pippox2
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '200':
          description: Username set successful
        '400' : { $ref: "#/components/responses/BadRequest" }

  /users/{userId}/pfp:
    put: 
      summary: set profile picture
      description: the user set the profile picture that other users will see while texting with him
      operationId: setMyPhoto
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                pfp:
                  type: string
                  format: binary
        required: true
      responses: 
        '200':
          description: Profile picture set successful
        '400' : { $ref: "#/components/responses/BadRequest" }

components:
  responses:
    BadRequest:   
      description: The request was not compliant with the documentation (eg. missing fields, etc)
  schemas:
    Message:
      type: object
      description: message sent by an user
      properties:
        status:
          type: string
          enum:
            - "seen"
            - "sent"
            - "sending"
        text:
          type: string
          description: testo del messaggio (opzionale)
          minLength: 1
          maxLength: 150
        media:
          $ref: '#/components/schemas/Media'
          description: media del messaggio (opzionale)
        time:
          description: time that message was sent 
          type: string
          format: date-time
          example: "11:23"
      anyOf:
        - required: ["text"]
        - required: ["media"]

    Media:
      type: object
      description: Oggetto che rappresenta un'immagine allegata al messaggio
      properties:
        url:
          type: string
          format: uri
          description: URL of image
        filename:
          type: string
          description: file image name
        mimeType:
          type: string
          description: image/png, image/jpeg
        size:
          type: integer
          description: image size in byte
      required:
        - url
        - mimeType

    Conversation: 
      type: array
      properties:
        partecipants:
          type:
            array
          items: 
            description: List of ID of the users that partecipate the conversation
            type: string
        messages:
          type:
            array
          items:
            description: List of messages sent by the users
    
    Group:
      allOf:
        - $ref: '#/components/schemas/Conversation'
        - type: object
          description: conversation with at least 2 users or more with option to set a name and a pic 
          properties:
            groupName:
              type: string
              description: Group name
              default: "New Group"
            participants:
              type: array
              items:
                type: string
              minItems: 2     
              maxItems: 100
          required:
            - participants


          
    






#TODO: 
#• getMyConversations
# getConversation
#• sendMessage
#• forwardMessage
#• commentMessage
#• uncommentMessage
#• deleteMessage
#• addToGroup
#• leaveGroup
#• setGroupName
#• setGroupPhoto
